version: "3.8"

services:
  postgres:
    image: postgres:15
    pull_policy: if_not_present
    hostname: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  app:
    build:
      context: .
      dockerfile: Dockerfile

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.0/24
